import os
import rasterio
import matplotlib.pyplot as plt
import numpy as np

if __name__ == '__main__':
    # --- File Paths ---
    input_tiff_path = "/srv/AB_YU/RS_07_Chad_Lake_Geohazards/06__apply_ml_te_to_real_data_GPU/TE_Precipitation_to_NDVI_GPU.tif"
    
    # The output folder is the same as the one generated by the previous script
    output_folder = "/srv/AB_YU/RS_07_Chad_Lake_Geohazards/06__apply_ml_te_to_real_data_GPU"
    output_plot_path = os.path.join(output_folder, "TE_Precipitation_to_NDVI_GPU_with_coords.png") # Changed filename

    # --- Plotting ---
    print(f"Reading raster data from: {input_tiff_path}")
    with rasterio.open(input_tiff_path) as src:
        te_map = src.read(1)
        # Mask out no-data values for plotting
        te_map_masked = np.ma.masked_equal(te_map, src.nodata)

        # Get geographic extent
        extent = [src.bounds.left, src.bounds.right, src.bounds.bottom, src.bounds.top]

        # Set font sizes to 2.5 times larger
        plt.rcParams.update({
            'font.size': 25,           # 2.5x larger base font
            'axes.titlesize': 40,      # 2.5x larger title
            'axes.labelsize': 30,      # 2.5x larger axis labels
            'xtick.labelsize': 20,     # 2.5x larger x-tick labels
            'ytick.labelsize': 20,     # 2.5x larger y-tick labels
            'legend.fontsize': 20,     # 2.5x larger legend
        })

        fig, ax = plt.subplots(1, 1, figsize=(12, 10))  # Slightly larger figure
        
        # Use a different colormap - 'plasma' for vibrant colors
        # Other options: 'inferno', 'magma', 'hot', 'coolwarm', 'RdYlBu_r'
        cmap = 'plasma'
        
        im = ax.imshow(te_map_masked, cmap=cmap, extent=extent)
        
        ax.set_title("Predicted Transfer Entropy\n(Precipitation to NDVI)", fontsize=40, pad=20)
        ax.set_xlabel("Longitude", fontsize=30, labelpad=15)
        ax.set_ylabel("Latitude", fontsize=30, labelpad=15)
        
        # Increase tick size and padding
        ax.tick_params(axis='both', which='major', labelsize=20, length=8, width=1.5, pad=10)
        
        # Add a colorbar with reduced thickness
        cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        cbar.set_label("Transfer Entropy (TE)", fontsize=25, rotation=90, labelpad=20)
        
        # Reduce thickness of colorbar (make it thinner)
        cbar.ax.tick_params(labelsize=20, width=0.5, length=6)  # Reduced thickness
        
        # Optional: Make the colorbar outline thinner
        cbar.outline.set_linewidth(0.5)
        
        plt.tight_layout()
        
        # --- Save the plot ---
        print(f"Saving plot to: {output_plot_path}")
        plt.savefig(output_plot_path, dpi=300, bbox_inches='tight')
        
    print("\nPlotting complete.")
